### PR TITLE
fix: Issue #95 with RemoteMediator First Load

### PR DESCRIPTION
**Pull request by AdamSHurwitz**
# Changes Summary

This resolves Issue #95. 

1. Disable Prepend loads that are not used in the sample. This will otherwise crash on the first load.
2. Set default index for the first load in Append loads. This will otherwise crash on the first load.
3. Remove RecyclerView flicker during loading state.

## 1. Disable Prepend loads

This error occurs on the first load since prepend is not enabled.

>  java.io.InvalidObjectException: Remote key and the prevKey should not be null

_Full error log_

> 2020-09-21 16:26:42.413 18648-18648/? E/codelabs.pagin: Unknown bits set in runtime_flags: 0x8000
2020-09-21 16:26:45.328 18648-18648/com.example.android.codelabs.paging E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.codelabs.paging, PID: 18648
    java.io.InvalidObjectException: Remote key and the prevKey should not be null
        at com.example.android.codelabs.paging.data.GithubRemoteMediator.load(GithubRemoteMediator.kt:56)
        at androidx.paging.RemoteMediatorAccessor.doLoad(RemoteMediatorAccessor.kt:96)
        at androidx.paging.RemoteMediatorAccessor$doLoad$1.invokeSuspend(Unknown Source:16)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:175)
        at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:137)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:108)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:308)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:318)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:250)
        at kotlinx.coroutines.ResumeOnCompletion.invoke(JobSupport.kt:1394)
        at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1529)
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:323)
        at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:240)
        at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:903)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
        at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

## 2. Set default index for the first load in Append loads.

This error occurs on the first load since the database has not yet been loaded with data.

>  java.io.InvalidObjectException: Remote key should not be null for APPEND

_Full error log_

> 2020-09-21 16:28:04.349 18779-18779/? E/codelabs.pagin: Unknown bits set in runtime_flags: 0x8000
2020-09-21 16:28:07.834 18779-18779/com.example.android.codelabs.paging E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.codelabs.paging, PID: 18779
    java.io.InvalidObjectException: Remote key should not be null for APPEND
        at com.example.android.codelabs.paging.data.GithubRemoteMediator.load(GithubRemoteMediator.kt:54)
        at androidx.paging.RemoteMediatorAccessor.doLoad(RemoteMediatorAccessor.kt:96)
        at androidx.paging.RemoteMediatorAccessor$load$$inlined$withLock$lambda$1.invokeSuspend(RemoteMediatorAccessor.kt:65)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:69)
        at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:184)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:108)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:308)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:318)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:250)
        at kotlinx.coroutines.ResumeOnCompletion.invoke(JobSupport.kt:1394)
        at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1529)
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:323)
        at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:240)
        at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:903)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
        at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

## 3. Remove RecyclerView flicker during loading state.

The flicker was occurring every time new data was loaded.

### CODE REVIEW

**Comment by johnjake** [comment]
in my case I remove the throw exception 

`val page = when (loadType) {
            LoadType.REFRESH -> {
                val remoteKeys = getRemoteKeyClosestToCurrentPosition(state)
                remoteKeys?.nextKey?.minus(1) ?: GITHUB_STARTING_PAGE_INDEX
            }
            LoadType.PREPEND -> return MediatorResult.Success(endOfPaginationReached = true)
            LoadType.APPEND -> {
                val remoteKeys = getRemoteKeyForLastItem(state)
                if (remoteKeys?.nextKey == null) {
                    return MediatorResult.Success(endOfPaginationReached = true)
                }
                remoteKeys.nextKey
            }
        }`

**Comment by CelikAbdullah** [comment]
> in my case I remove the throw exception and replace them `return MediatorResult.Success(endOfPaginationReached = true)`, on both APPEND and PREPEND
> 
> ```
>      val page = when (loadType) {
>         LoadType.REFRESH -> {
>             val remoteKeys = getRemoteKeyClosestToCurrentPosition(state)
>             remoteKeys?.nextKey?.minus(1) ?: GITHUB_STARTING_PAGE_INDEX
>         }
>         LoadType.PREPEND -> return MediatorResult.Success(endOfPaginationReached = true)
>         LoadType.APPEND -> {
>             val remoteKeys = getRemoteKeyForLastItem(state)
>             if (remoteKeys?.nextKey == null) {
>                 return MediatorResult.Success(endOfPaginationReached = true)
>             }
>             remoteKeys.nextKey
>         }
>     }
> ```

Yees, I did the same. Happy to see that someone did the same as I did. That solution worked also for me.

**Comment by doomtrooper** [comment]
What is the correct approach here?

**Comment by AdamSHurwitz** [comment]
@johnjake and @CelikAbdullah, this is a good solution as well!

**Comment by android-taoge** [comment]
@johnjake and @CelikAbdullah , LoadType.PREPEND  : return  MediatorResult.Success(endOfPaginationReached = true)  lead  loadMore trigger not work in first launch  .
this is my solution:
 val page = when (loadType) {
            LoadType.REFRESH -> {
                val remoteKeys = getRemoteKeyClosestToCurrentPosition(state)
                remoteKeys?.nextKey?.minus(1) ?: GITHUB_STARTING_PAGE_INDEX
            }
            LoadType.PREPEND -> {
                val remoteKeys = getRemoteKeyForFirstItem(state)
                        ?: return MediatorResult.Success(endOfPaginationReached = false)
                remoteKeys.prevKey ?: return MediatorResult.Success(endOfPaginationReached = true)
                remoteKeys.prevKey
            }
            LoadType.APPEND -> {
                val remoteKeys = getRemoteKeyForLastItem(state)
                if (remoteKeys?.nextKey == null) {
                    return MediatorResult.Success(endOfPaginationReached = false)
                }
                remoteKeys.nextKey
            }

        }

**Comment by android-taoge** [comment]
### LoadType.APPEND -> return  MediatorResult.Success(endOfPaginationReached = true) , lead to load more trigger does not work at first launch.

> here 's my code :
``` 
val page = when (loadType) {
            LoadType.REFRESH -> {
                val remoteKeys = getRemoteKeyClosestToCurrentPosition(state)
                remoteKeys?.nextKey?.minus(1) ?: GITHUB_STARTING_PAGE_INDEX
            }
            LoadType.PREPEND -> {
                val remoteKeys = getRemoteKeyForFirstItem(state)
                        ?: return MediatorResult.Success(endOfPaginationReached = false)
                remoteKeys.prevKey ?: return MediatorResult.Success(endOfPaginationReached = true)
                remoteKeys.prevKey
            }
            LoadType.APPEND -> {
                val remoteKeys = getRemoteKeyForLastItem(state)
                if (remoteKeys?.nextKey == null) {
                    return MediatorResult.Success(endOfPaginationReached = false)
                }
                remoteKeys.nextKey
            }

        }
```

**Pull request closed without merging**
